# Generated by Django 3.0.6 on 2020-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200531_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='course_images'),
        ),
    ]
